spring：
  profiles:
    active:
    - dev
---
spring：
  profile:dev 
  application:
    name:microservicecloud-config-mpj-dev
---
spring：
  profile:test 
  application:
    name:microservicecloud-config-mpj-dev
#请保存味utf-8格式
