spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
aaa: nimabi
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
aaa: nimabi